### ISSUE TITLE
Add Finish FMI stations

### ISSUE THREAD

**Issue by AdamRJensen** [AssessingSolar/solarstations#236]
https://en.ilmatieteenlaitos.fi/weather-observations

**Comment by IoannisSifnaios** [comment]
@AdamRJensen, has somebody told you that they are actually doing DNI and DHI measurements? On their website, they give very little information, and when trying to download solar irradiance data, they only have GHI, LWD, and UV. 

![image](https://github.com/user-attachments/assets/ac4766f5-d816-4557-b72a-3a8cd87b95b9)

I am not convinced...

**Comment by AdamRJensen** [comment]
I have sent an email to contacts at the University of Turku.

**Comment by IoannisSifnaios** [comment]
Based on the email from Turku, there are three Tier 1 active stations in 2024. Data can be accessed [here](https://en.ilmatieteenlaitos.fi/download-observations).

Just for documentation:
* The website is not very user-friendly in identifying historical measurements. When I was trying to figure out when the Tier 1 stations started measuring DNI, more stations were popping up for some years, so it is possible that historical DNI data are available for more locations.
* Also, there are a number of stations measuring only GHI and DHI, but since they don't give specific information on the instruments used, I did not include them.

**Comment by AdamRJensen** [comment]
One of the stations is duplicate: the space station one. I suggest consulting the two websites to see how best to merge the info. I suggest keeping the comment about poor data quality.
